### ISSUE TITLE
Sparse Convolution Implementation

### ISSUE THREAD

**Issue by johnny8376** [StanfordVL/MinkowskiEngine#38]
Hi,
Thank you so much for your code.

I have several questions regarding to the sparse conv and submanifold conv. According to my understanding on Submanifold Sparse Convolutional Networks, sparse conv should have the same output like standard conv but sparse conv may bring computational benefits. 

1. Does MinkowskiConvolution use submanifold convolution as default?
2. How would you implement the sparse conv since I didn't find any related code? For example, let out_coords_key include in_coords_key's neighborhood?

**Comment by chrischoy** [comment]
So let's go over the generalized sparse convolution quickly https://stanfordvl.github.io/MinkowskiEngine/generalized_sparse_conv.html#id2

For all latex code define inside $$, use http://mathb.in/ to render them online.

The input coordinates and output coordinates can be defined arbitrarily as $\mathcal{C}^\text{in}$ and $\mathcal{C}^\text{out}$. There's no consistent definition in here that a sparse convolution has to give out the same result as the regular convolution. From my experience, if you expand the coordinate space so that the sparse convolution gives the same result as the standard discrete dense convolution (regular conv2d or conv3d), the computation increases rapidly while it gives no performance increase. So I would not go that route unless you have a specific reason for that.

1. By default, it uses the same input coordinates for output $\mathcal{C}^\text{out} = \mathcal{C}^\text{in}$.

2. As I mentioned, I would not go that route. If you need, I would simply use `.dense()` function to convert the sparse tensor to a dense one and do convolution after you decrease the resolution of the space significantly. However, if you absolutely need that, I can make a cleaner API function.

**Comment by johnny8376** [comment]
Thanks for your quick reply. 
I was using the terminology of sparse conv and submanifold conv in Submanifold Sparse Convolutional Networks.  I just want to make sure I can use your library to reproduce other network. 
I appreciate your generalized framework. The current API looks quit flexible to me. There's no need to include such expensive operator here.

**Comment by lshiwjx** [comment]
@chrischoy Hi, Thanks for your code. 
I feel that the MinkowskiConvolutionTranspose(generate_new_coords=True) is equivalent to the Dense Convolution regardless of the negative coordinates of the output. Am I correct?

**Comment by chrischoy** [comment]
No it is not equivalent. The input is the sparse tensor.

**Comment by lshiwjx** [comment]
@chrischoy Thanks for your reply. 

I mean that in your implement, the input coordinates and output coordinates are the same. But for regular convolution, the out_coords_key includes in_coords_key's neighborhood. 

As you have mentioned, in your experiments, expanding the output coordinate space will harm the performance, but I want to try this in my tasks where the input is very sparse. 

I found that it seems the MinkowskiConvolutionTranspose(generate_new_coords=True) can achieve this function, i.e., the regular convolution, because the output coordinates of the transpose convolution are expanded.  Am I correct?
