### ISSUE TITLE
Questions about segmentation metric.

### ISSUE THREAD

**Issue by SUZhaoyu** [StanfordVL/MinkowskiEngine#85]
Hi,
I'm wondering what happens if a voxel is occupied by more than one point for segmentation tasks? Referring to the paper, seems that Minkowski Engine simply ignore those voxels during the training phase, these predictions are also excluded from final evaluation?

Thanks.
Tony

**Comment by chrischoy** [comment]
We don't ignore those points, and it is not ambiguous to use those points. However, we ignore points with multiple "labels" in some evaluation. e.g., chair and desk in the same voxel.

For ScanNet, we simply copy labels for all points within a voxel, since the test procedure requires one label for each point.

For the rest, we ignore those voxels during, as it is an ambiguous behavior.

**Comment by SUZhaoyu** [comment]
Ok. Understood, thanks for the reply. But I am wondering, will this cause the inaccurate evaluation results? Since the boundaries between objects usually are the most difficult part to make an accurate prediction, while they are ignored in the voxel based method.

**Comment by chrischoy** [comment]
Right, there would be some differences between the point-wise evaluation and voxel-wise evaluation. However, from the ScanNet 2cm test set results, it seems that the differences are very small between the point-wise evaluation and voxel-wise evaluation.

There could be multiple reasons. 1. the number of voxels on the boundary is very small compared with the voxels inside objects. 2. hard assigning all points on the boundary to the argmax label seems to cancel out the differences in to end.

**Comment by SUZhaoyu** [comment]
I see, thank you for the explanation.
